### ISSUE TITLE
VL Performance Tab: Retention Cascade.

### ISSUE THREAD

**Issue by Yabayabadoo** [ICPI/VL_Tool_FY18#26]
![image](https://user-images.githubusercontent.com/34660366/48948193-b0803c80-ef01-11e8-8731-6ece2c7495b6.png)

When the Sex slicer is filtered, the above happens to the Retention cascade:
1. Why would 'Total' values disappear when there is data in the age bands to the left?
2. Can we unlink the pregnant women Retention values from the sex slicer?

**Comment by anu87** [comment]
can you tell which OU/PSNU had this error? I am not sure what's wrong and unable to replicate the error.

Unlinking - I'll have to change the pivot table for this - since pregnant & age data are being pulled from the same pivot table. Is it okay if I do this after releasing the tool because I'll have then check if any else changes

**Comment by Yabayabadoo** [comment]
I'll send an email about country as that is sensitive

**Comment by anu87** [comment]
done
