### ISSUE TITLE
Quality Systems Tab: PSNU Summary table not populating

### ISSUE THREAD

**Issue by Yabayabadoo** [ICPI/VL_Tool_FY18#7]
![image](https://user-images.githubusercontent.com/34660366/48803360-b991c380-ecdf-11e8-9cee-d5fced68fdf1.png)
 
This table should show the total PSNU average and  upper and lower ranges, but does not populate for any selected countries. Also, the total PSNU average is inclusive of all sites right? Not just our top 25th percentile sites. The ranges was supposed to account for VL coverage and suppression across all sites with data...

**Comment by anu87** [comment]
This table is appears alongside site level data table, since the slicers between psnu_im & site_im can't be connected, I disconnected this psnu table from other slicers and connected it to site level table via the *Selected PSNU* cell on top. I have added a note in the dashboard now - clarifying the same.

**Comment by Yabayabadoo** [comment]
Great, thanks Anu

**Comment by Yabayabadoo** [comment]
Hi Anu, the approach you used makes sense, but the table not populating does not. If the selected PSNU cell is the reference for the table, why isn't it populating?

**Comment by anu87** [comment]
Yes, I am fixing that right now. Some of the slicers are still connected to that pivot table that is causing the error.
